pipelines:
  - name: First_Pipeline_Long_Pipeline_Name_Very_Long_Again
    steps:
      - name: First_Step
        type: Bash
        configuration:
          integrations:
            - name: simple_mail
        execution: 
          onExecute:
            - echo "Step 1"
            - sleep 5s
   
